#!/usr/bin/env bash
#Does multiply kills
terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
root@c8fe86d4fd39:~/alu-shell/processes_and_signals# cat 11-manage_my_process 
#!/usr/bin/env bash 
#managing process
start () {                                         
    ./manage_my_process &                          
    echo $! > /var/run/my_process.pid              
    echo "manage_my_process started"               
}                                                  
                                                   
stop () {                                          
    pkill -f "./manage_my_process"                 
    rm /var/run/my_process.pid                     
    echo "manage_my_process stopped"               
}                                                  
                                                   
restart () {                                       
    pkill -f "./manage_my_process"                 
    rm /var/run/my_process.pid                     
    ./manage_my_process &                          
    echo $! >> /var/run/my_process.pid             
    echo "manage_my_process restarted"             
}
case "$1" in                                       
   start) start ;;                                 
   stop)  stop;;                                   
   restart) restart;;                              
   *) echo "Usage: manage_my_process {start|stop|r\
estart}"                                           
      ;;                                           
esac

